apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "nvidia-gpu-list-exporter.fullname" . }}
  namespace: {{ include "nvidia-gpu-list-exporter.namespace" . }}
  labels:
    {{- include "nvidia-gpu-list-exporter.labels" . | nindent 4 }}
spec:
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "nvidia-gpu-list-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include "nvidia-gpu-list-exporter.env" . | sha256sum }}
      labels:
        {{- include "nvidia-gpu-list-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nvidia-gpu-list-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.nvidiaRuntime.runtimeClassName }}
      runtimeClassName: {{ . }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      hostPID: {{ .Values.hostPID }}
      containers:
        - name: nvidia-gpu-list-exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "nvidia-gpu-list-exporter.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --host={{ .Values.host }}
            - --port={{ .Values.port }}
            - --interval={{ .Values.exporter.interval }}
            - --timeout={{ .Values.exporter.timeout }}
            {{- if .Values.exporter.nvidiaSmiPath }}
            - --nvidia-smi-path={{ .Values.exporter.nvidiaSmiPath }}
            {{- end }}
            {{- if .Values.exporter.hostnameOverride }}
            - --hostname={{ .Values.exporter.hostnameOverride }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.port }}
              protocol: TCP
          env:
            {{- include "nvidia-gpu-list-exporter.env" . | nindent 12 }}
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: metrics
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
            successThreshold: {{ .Values.healthCheck.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 
