apiVersion: v1
kind: Service
metadata:
  name: {{ include "nvidia-gpu-list-exporter.fullname" . }}
  namespace: {{ include "nvidia-gpu-list-exporter.namespace" . }}
  labels:
    {{- include "nvidia-gpu-list-exporter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "nvidia-gpu-list-exporter.selectorLabels" . | nindent 4 }} 