{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nvidia-gpu-list-exporter.serviceAccountName" . }}
  namespace: {{ include "nvidia-gpu-list-exporter.namespace" . }}
  labels:
    {{- include "nvidia-gpu-list-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 